# From https://github.com/RobRaesemann/FLEDGE-IOT-Docker

services:
  fledge:
    image: robraesemann/fledge
    environment:
      - FLEDGE_ROOT=/usr/local/fledge
    volumes:
      - fledge:/usr/local/fledge
    ports:
      - 8081:8081 # Fledge management API
      - 6683:6683 # Fledge south API
      - 8080:8080 # Optional: Additional API if configured

  fledge-gui:
    image: robraesemann/fledge-gui
    ports:
      - 80:80 # Fledge GUI

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  fledge:
