services:
  fledge:
    image: robraesemann/fledge
    environment:
      - FLEDGE_ROOT=/usr/local/fledge
    volumes:
      - fledge:/usr/local/fledge
    ports:
      - 8081:8081
      - 1995:1995
      - 8080:8080

  fledge-gui:
    image: robraesemann/fledge-gui
    ports:
      - 80:80

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  fledge:
