# From https://github.com/RobRaesemann/FLEDGE-IOT-Docker
services:
  comms_gw:
    build:
      context: .
      dockerfile: fledge/Dockerfile.fledge_power
    platform: linux/amd64
    container_name: og-comms_gw
    environment:
      - FLEDGE_ROOT=/usr/local/fledge
      - TZ=${TZ}
    volumes:
      - fledge:/usr/local/fledge
      #- ./mqtt-readings-binary:/usr/local/fledge/python/fledge/plugins/south/mqtt-readings-binary
    ports:
      - 8081:8081 # Fledge management API
      - 6685:6685 # Fledge south API
      - 6683:6683
      - 8080:8080 # Optional: Additional API if configured
      - 8082:8082 # south MQTT publish plugin
    entrypoint: >
      sh -c "pg_isready -q || service postgresql start &&
       sudo -u postgres createuser -d $(whoami) || echo 'User already exists' &&
       /usr/local/fledge/start.sh"

  comms_gw-gui:
    container_name: og-comms_gw-gui
    image: robraesemann/fledge-gui:2.6.0
    environment:
      - TZ=${TZ}
    ports:
      - 80:80 # Fledge GUI

  mosquitto:
    image: eclipse-mosquitto
    container_name: og-mosquitto
    environment:
      - TZ=${TZ}
    ports:
      - 1884:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  comms_gw-api:
    container_name: og-comms_gw-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000" # FastAPI Swagger
    depends_on:
      comms_gw:
        condition: service_started
    environment:
      - COMMS_GW_BASE_URL=${COMMS_GW_BASE_URL:-http://comms_gw:8081}
      - FLEDGE_USERNAME=${FLEDGE_USERNAME:-admin}
      - FLEDGE_PASSWORD=${FLEDGE_PASSWORD:-fledge}
      - TZ=${TZ}
    volumes:
      - .:/app
    command: >
      bash -c "
       uvicorn main:app --host 0.0.0.0 --port 8000 & 
       until curl -s -o /dev/null -w '%{http_code}' http://comms_gw:8081/fledge/ping | grep -q '200'; do
         echo 'Waiting for Fledge to be online...';
         sleep 2;
       done;
       echo 'Fledge is online. Proceeding with configuration...';
         curl -X PUT 'http://comms_gw:8081/fledge/category/rest_api/authMethod' -H 'Content-Type: application/json' -d '{\"value\": \"password\"}' &&
         curl -X PUT 'http://comms_gw:8081/fledge/category/rest_api/authentication' -H 'Content-Type: application/json' -d '{\"value\": \"mandatory\"}' &&
         curl -X PUT 'http://comms_gw:8081/fledge/restart' &&
         tail -f /dev/null"

  mqtt-seed-stem-json-emulator:
    build: ./mqtt-publisher
    container_name: og-mqtt-seed-stem-json-emulator
    environment:
      PDS_INTERVAL: 60 # Default interval for PDS in seconds
      ADS_INTERVAL: 10 # Default interval for ADS in seconds
      MQTT_BROKER: "mosquitto" # Replace with your MQTT broker hostname or IP
      MQTT_PORT: 1883 # MQTT broker port
      MQTT_DEVICE: ${MQTT_DEVICE} #list of MQTT devices to simulate data
      TZ: ${TZ}
    volumes:
      - ./mqtt-publisher/config_pds.json:/app/config_pds.json
      - ./mqtt-publisher/config_ads.json:/app/config_ads.json
      - ./mqtt-publisher/config_dds.json:/app/config_dds.json
    depends_on:
      - mosquitto

  mqtt-seed-stem-binary-emulator:
    container_name: og-mqtt-seed-stem-binary-emulator
    build:
      context: https://${GITHUB_TOKEN}@github.com/OrxaGridMicroservices/SEED-STEM-Emulator.git#main
    platform: linux/amd64
    command: python /app/main.py --data_type random --phase_version Ph7

    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_DEVICE=${MQTT_DEVICE}
      - DEVICE_TYPE=${DEVICE_TYPE}
      - MQTT_TOPICS=${MQTT_TOPICS}
      - ADS_INTERVAL=${ADS_INTERVAL}
      - PDS_INTERVAL=${PDS_INTERVAL}
      - PQS_INTERVAL=${PQS_INTERVAL}
      - DDS_INTERVAL=${DDS_INTERVAL}
      - TZ=${TZ}
    tty: true
    restart: always # Added restart policy
    stdin_open: true

volumes:
  fledge:
